PRAGMA foreign_keys = ON;

CREATE TABLE scenario (
	key INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   	shortname TEXT UNIQUE NOT NULL ,
	desc TEXT
);

CREATE TABLE links (
	key INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	from_key INTEGER NOT NULL,
	to_key INTEGER NOT NULL,
	desc TEXT NOT NULL,
	FOREIGN KEY (from_key)
		REFERENCES scenario (key)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (to_key)
		REFERENCES scenario (key)
			ON DELETE CASCADE
			ON UPDATE NO ACTION
);

CREATE TABLE history (
	key INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	timestamp DATE DEFAULT (datetime('now','localtime')) NOT NULL,
	level INTEGER NOT NULL,
	desc TEXT NOT NULL
);